import type { Product } from "@/lib/types";

export const products: Product[] = [
  {
    id: "kb-eucalyptus-lift",
    slug: "eucalyptus-lift",
    name: "Eucalyptus Lift",
    shortName: "Lift",
    profile: ["Fresh", "Herbaceous"],
    notes: ["eucalyptus", "spearmint", "juniper"],
    accent: "#66d8c6",
    tint: "#dff8f2",
    price: 24,
    size: "10 mL",
    intensity: "Balanced",
    description: "A cool, green aromatic roll-on built for the walk from street clothes to training mode.",
    ritual: "Roll lightly onto pulse points, rub palms together, inhale, then get moving.",
    badge: "Gym-bag favorite",
    workoutMatches: ["High Intensity", "Heavy Lifting"],
  },
  {
    id: "kb-rosemary-drive",
    slug: "rosemary-drive",
    name: "Rosemary Drive",
    shortName: "Drive",
    profile: ["Herbaceous", "Fresh"],
    notes: ["rosemary", "lemon peel", "basil"],
    accent: "#9ecf88",
    tint: "#eef8e8",
    price: 24,
    size: "10 mL",
    intensity: "Light",
    description: "Bright herbs and citrus with a clean, athletic finish that stays close to the skin.",
    ritual: "Apply before warm-up or after a quick locker-room reset.",
    badge: "Bright + clean",
    workoutMatches: ["High Intensity", "Yoga / Mobility"],
  },
  {
    id: "kb-pine-cedar-ground",
    slug: "pine-cedar-ground",
    name: "Pine + Cedar Ground",
    shortName: "Ground",
    profile: ["Earthy"],
    notes: ["pine needle", "cedarwood", "vetiver"],
    accent: "#355b46",
    tint: "#dfe8df",
    price: 26,
    size: "10 mL",
    intensity: "Bold",
    description: "Dry woods, cool forest air, and a compact roller made for heavy sessions and late-night training.",
    ritual: "Roll once at wrists and collar line; keep the scent personal, not room-filling.",
    badge: "Deepest profile",
    workoutMatches: ["Heavy Lifting"],
  },
  {
    id: "kb-lavender-reset",
    slug: "lavender-reset",
    name: "Lavender Reset",
    shortName: "Reset",
    profile: ["Calming", "Herbaceous"],
    notes: ["lavender", "clary sage", "bergamot"],
    accent: "#a99ad8",
    tint: "#f0ecfb",
    price: 24,
    size: "10 mL",
    intensity: "Light",
    description: "Soft lavender and herbal citrus for cooldowns, mobility work, and the transition out of training mode.",
    ritual: "Use after training, during stretching, or whenever you want a lighter aromatic reset.",
    badge: "Cooldown pick",
    workoutMatches: ["Yoga / Mobility"],
  },
  {
    id: "kb-thyme-spark",
    slug: "thyme-spark",
    name: "Thyme Spark",
    shortName: "Spark",
    profile: ["Herbaceous", "Earthy"],
    notes: ["thyme", "black spruce", "grapefruit"],
    accent: "#cf8b4f",
    tint: "#f7eadf",
    price: 25,
    size: "10 mL",
    intensity: "Balanced",
    description: "A sharper botanical profile with resinous depth and a bright citrus edge.",
    ritual: "A compact pre-session scent ritual for days you want something less expected.",
    badge: "Most distinctive",
    workoutMatches: ["High Intensity", "Heavy Lifting"],
  },
];

export const profiles = ["All", "Fresh", "Earthy", "Herbaceous", "Calming"] as const;

export function getProduct(slug: string) {
  return products.find((product) => product.slug === slug);
}
